### ISSUE TITLE
Indicador de dinero no se actualiza

### ISSUE THREAD

**Issue by sergio-ic** [Marchin/DrinkNShoot#11]
![imagen](https://user-images.githubusercontent.com/17152612/49541682-47f66f80-f8b2-11e8-91a6-cb270e9acee2.png)

Descripcion:
El indicador de dinero no aumenta, pese a que maté a varios cuervos y a que consigué ranks (como muestra imagen). Al completar stage de hecho se me mostraba el cash earned correcto.

Resultado Esperado:
Que indicador de dinero se actualice acorde a las muertes de cuervos y ranks

**Comment by Ignacio-Mosconi** [comment]
La idea es que el jugador adquiere el dinero **luego de completar una etapa** - no mientras la está jugando. De esta forma, es recompensado monetariamente de forma posterior a la finalización de la misma; por ende, si llega a matar cuervos pero no alcanza el mínimo necesario, no ganará dinero. El indicador del _HUD_, entonces, muestra la cantidad acumulada de plata que se va adquiriendo al completar las _"stages"._ Si le parece poco claro (o cree que ganar el dinero a medida que se matan a los cuervos es una idea mejor), se puede modificar.

**Comment by sergio-ic** [comment]
Entiendo lo que decís y de hecho después de probarlo algunas veces en el juego me quedó claro que era así. Pero entonces... si durante las etapas con el dinero no se puede realizar nada (las compras suceden en el store) y este no se modifica mientras se juega, ¿qué sentido tiene que aparezca ahí? Esa es la duda que tal vez habría que pensar. Lo vemos hoy en clase si te parece.
