### ISSUE TITLE
Falta cartel de Game Over - [Windows 10 x64] - [Development]

### ISSUE THREAD

**Issue by Pailott** [Marchin/DrinkNShoot#2]
![error al final del juego](https://user-images.githubusercontent.com/44702759/48230887-3d1bee00-e38b-11e8-83d7-84bbb80e2a64.png)
**Descripcion:**
Al finalizar el juego, después de pasar los 2 niveles, te salta este error y tenes que cerrarlo.

**Pasos de Reproducción:**
1. Iniciar desde la partida 2
2. Ganar la partida.
3. Aparece el error en vez de un cartel de game over.

**Repro Rate:** 100%

**Resultado Esperado:**
Que salte un cartel de Game Over y poder regresar a la pantalla de inicio para jugar otra partida.

**Comment by Pailott** [comment]
Buenos días, por favor pasar el label open a fixed.
Los tickets los cerraremos al verificar los bugs.
Muchas gracias

**Comment by Ignacio-Mosconi** [comment]
Quisiera saber si se ha logrado reproducir nuevamente el _bug_ en cuestión, dado a que ya se implementó una forma de solucionarlo.
