### ISSUE TITLE
Superposición del arnés con el caballo - [Windows 10 x64] - [Gráfico] 

### ISSUE THREAD

**Issue by Pailott** [Marchin/DrinkNShoot#3]
![madera sobresale](https://user-images.githubusercontent.com/44702759/48307387-76d72b00-e52a-11e8-97d8-2dc7c8593b0f.png)
**Descripcion:**
Durante cualquiera de los 2 niveles se nota una madera sobresaliendo del caballo

**Pasos de Reproducción:**
1. Iniciar en cualquiera de los niveles.
2. Pasar la primer ronda.
3. Cuando tengas la cara libre mirar al Caballo.

**Repro Rate:** 100%

**Resultado Esperado:**
Las maderas seguramente simulan el arnés, pero parece una fractura expuesta.

**Comment by Pailott** [comment]
> ![madera sobresale](https://user-images.githubusercontent.com/44702759/48307387-76d72b00-e52a-11e8-97d8-2dc7c8593b0f.png)
> **Descripcion:**
> Durante cualquiera de los 2 niveles se nota una madera sobresaliendo del caballo
> 
> **Pasos de Reproducción:**
> 
> 1. Iniciar en cualquiera de los niveles.
> 2. Pasar la primer ronda.
> 3. Cuando tengas la cara libre mirar al Caballo.
> 
> **Repro Rate:** 100%
> 
> **Resultado Esperado:**
> Las maderas seguramente simulan el arnés, pero parece una fractura expuesta.

**Comment by Ignacio-Mosconi** [comment]
El inconveniente ha sido parcialmente solucionado a través de la eliminación de las maderas que se superponían con el caballo. En un futuro se evaluará la posibilidad de añadir unas riendas que sujeten al caballo de forma más realista.
