### ISSUE TITLE
Resuelve mal la compra de Bait - [Windows 10 x64] - [menu/validation]

### ISSUE THREAD

**Issue by Pailott** [Marchin/DrinkNShoot#4]
[**Video 1**](https://drive.google.com/file/d/158XRjAHdJLGYz_djs8TaNWKWJzc-pUbU/view?usp=sharing)
[**Video 2**](https://drive.google.com/file/d/1xdXA9mK6cLCFX3CFpRmjNmej4HNFHaD9/view?usp=sharing)

**Descripcion:**
El calculo de precio del bait es erróneo, me salta el cartel de que no tengo plata suficiente.

**Pasos de Reproducción:**
1. Entrar al Store con 100 o mas de cash.
2. Intentar comprar bait.
3. Aparece el error de que no tengo plata suficiente.

**Repro Rate:** 100%

**Resultado Esperado:**
Comprar el Bait

**Comment by Ignacio-Mosconi** [comment]
El cálculo se resolvía incorrectamente debido a que el ítem en cuestión no se encontraba totalmente implementado; ahora ya es posible comprarlo.
