### ISSUE TITLE
No condicen el dibujo del contador de Balas - [Windows x64] - [UI]

### ISSUE THREAD

**Issue by Pailott** [Marchin/DrinkNShoot#6]
![balas](https://user-images.githubusercontent.com/44702759/48307658-38446f00-e530-11e8-8463-860f5558cbf3.png)

**Descripción:**
El contador de balas tiene el dibujo del revolver y debería tener el de una bala.

**Pasos de Reproducción:**
1. Iniciar cualquier nivel.
2. Comprar la Winchester.
3. Mirar el contador de balas con la Wichester puesta.

**Repro Rate:** 100%

**Resultado Esperado:**
El contador de balas debería tener el dibujo de una bala.

**Comment by Ignacio-Mosconi** [comment]
El problema ha sido resuelto en la versión 0.12, donde el indicador de balas muestra un dibujo del arma equipada en el momento.
