### ISSUE TITLE
Faltan Animaciones del Carro y el Caballo - [Win x64] - [Graficos]

### ISSUE THREAD

**Issue by Pailott** [Marchin/DrinkNShoot#9]
[**Video**](https://drive.google.com/open?id=1pnyVOyyoySkD8ab2YKTDC45lxsOQbSYn)

**Descripcion:**
Ni el caballo, ni las ruedas del carro se mueven

**Pasos de Reproducción:**
1. Entrar a cualquier level.
2. Mirar el caballo y las ruedas del carro.

**Repro Rate:** 100%

**Resultado Esperado:**
Que se muevan las ruedas del carro y el caballo galope o se mueva el crin.

**Comment by Ignacio-Mosconi** [comment]
El caballo ya cuenta con una animación sencilla; las ruedas del carruaje, por otra parte, serán animadas en un futuro.
